
service: gitlab-app

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  profile: devqa
  region: ap-southeast-1
  environment:
      tableName: ${self:custom.tableName}
  iamRoleStatements:
     - Effect: Allow
       Action:
            - dynamodb:*
       Resource: '*'




custom:
    tableName: gitlab


functions:
    get-gitlab-data:
        handler: app/controller/get-gitlab-data.handler
        events:
            - http:
                  path: get-gitlab-data
                  method: GET
                  cors: true                   

    gitlab-controller:
        handler: app/controller/gitlab-controller.handler
        events:
            - http:
                  path: gitlab-controller
                  method: POST
                  cors: true


resources:
    Resources:
        MyDynamoDbTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: timestamp
                      AttributeType: N                    
                KeySchema:
                    - AttributeName: timestamp
                      KeyType: HASH                                           
                BillingMode: PAY_PER_REQUEST

